In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
from datetime import datetime

import scipy.stats as stats
from scipy.signal import detrend
import scipy.stats as stats


turbodir = '/nfs/turbo/seas-hutsona/shansen/sh_outputs/'

In [2]:
# table = pd.read_csv(turbodir + 'stormtable.csv', index_col=0)
table = pd.read_csv(turbodir + 'stormtable_mslpert.csv', index_col=0)
table.columns

Index(['year', 'month', 'day', 'hour', 'lon', 'lat', 'loc', 'year_start_GLR',
       'month_start_GLR', 'day_start_GLR', 'hour_start_GLR', 'year_end_GLR',
       'month_end_GLR', 'day_end_GLR', 'hour_end_GLR', 'storm_duration_GLR',
       'year_strongest_GLR', 'month_strongest_GLR', 'day_strongest_GLR',
       'hour_strongest_GLR', 'mslp_strongest_GLR',
       '<--Is this when it's strongest in the GLR?', 't2m', 'tcwv', 'tp',
       'd2m', 'msl', 'NAO', 'NPGO', 'PDO', 'PNA', 'SOI', 'Unsupervised Class',
       'AO', 'ENSO', 'NAO Phase', 'NPGO Phase', 'PDO Phase', 'PNA Phase',
       'SOI Phase', 'ENSO Phase', 'AO Phase'],
      dtype='object')

In [3]:
telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'ENSO','AO']

for telecon in telelist:

    p_mask = table[f'{telecon} Phase'] == 'Positive'
    n_mask = table[f'{telecon} Phase'] == 'Negative'
    neut_mask = table[f'{telecon} Phase'] == 'Neutral'

    # Use the mask to filter rows
    pos = table[p_mask]
    neg = table[n_mask]
    neut = table[neut_mask]


    t2m_p = pos['t2m']
    t2m_n = neg['t2m']
    t2m_neut = neut['t2m']

    msl_p = pos['msl']
    msl_n = neg['msl']
    msl_neut = neut['msl']

    tp_p = pos['tp']
    tp_n = neg['tp']
    tp_neut = neut['tp']

    d2m_p = pos['d2m']
    d2m_n = neg['d2m']
    d2m_neut = neut['d2m']

    tcwv_p = pos['tcwv']
    tcwv_n = neg['tcwv']
    tcwv_neut = neut['tcwv']


    t2m, p_t2m = stats.f_oneway(t2m_p, t2m_n, t2m_neut)
    msl, p_msl = stats.f_oneway( msl_p, msl_n, msl_neut)
    tp, p_tp = stats.f_oneway( tp_p, tp_n, tp_neut)
    tp_non, p_tp_non = stats.kruskal(tp_p, tp_n, tp_neut)
    d2m, p_d2m = stats.f_oneway( d2m_p, d2m_n, d2m_neut)
    tcwv, p_tcwv = stats.f_oneway( tcwv_p, tcwv_n, tcwv_neut)



    print('Telecon: ', telecon)
    print('t2m: ', p_t2m)
#     print('    Stat: ', t2m)
    print('msl: ', p_msl)
#     print('    Stat: ', msl)
    print('tp: ', p_tp)
#     print('    Stat: ', tp)
    print('d2m: ', p_d2m)
#     print('    Stat: ', d2m)
    print('tcwv: ', p_tcwv)
#     print('    Stat: ', tcwv)
    print('')
    print('tp non-par: ', p_tp_non)
    print('')

Telecon:  NAO
t2m:  0.004213489434908123
msl:  0.319298807082584
tp:  0.24190128816960177
d2m:  0.0018071636305750946
tcwv:  0.015195392814704634

tp non-par:  0.13873041171617626

Telecon:  NPGO
t2m:  0.0011291571980858231
msl:  0.7009646766580395
tp:  0.8406321626736966
d2m:  0.0005908753543520824
tcwv:  0.034691740384584405

tp non-par:  0.8236076601261597

Telecon:  PDO
t2m:  0.45606790176634504
msl:  0.38729334633274126
tp:  0.25667035645908853
d2m:  0.4779339961034075
tcwv:  0.49194121270273494

tp non-par:  0.250094679106398

Telecon:  PNA
t2m:  0.21981278106128188
msl:  0.443828784432689
tp:  0.6998425088719811
d2m:  0.24266498687311908
tcwv:  0.05570863685663326

tp non-par:  0.48932120909421273

Telecon:  ENSO
t2m:  0.5461006275260409
msl:  0.9073487487738213
tp:  0.9264110462411905
d2m:  0.5629066120741302
tcwv:  0.5452597361803462

tp non-par:  0.9931876870912448

Telecon:  AO
t2m:  0.0006768613065856232
msl:  0.278573171044456
tp:  0.0001765551224671049
d2m:  3.199224766526579e-05
tcwv:  4.137466641850311e-05

tp non-par:  5.736607866881798e-05

# Tukey HSD

In [4]:
telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'SOI', 'ENSO']

for telecon in telelist:

    p_mask = table[f'{telecon} Phase'] == 'Positive'
    n_mask = table[f'{telecon} Phase'] == 'Negative'
    neut_mask = table[f'{telecon} Phase'] == 'Neutral'

    # Use the mask to filter rows
    pos = table[p_mask]
    neg = table[n_mask]
    neut = table[neut_mask]


    t2m_p = pos['t2m']
    t2m_n = neg['t2m']
    t2m_neut = neut['t2m']

    msl_p = pos['msl']
    msl_n = neg['msl']
    msl_neut = neut['msl']

    tp_p = pos['tp']
    tp_n = neg['tp']
    tp_neut = neut['tp']

    d2m_p = pos['d2m']
    d2m_n = neg['d2m']
    d2m_neut = neut['d2m']

    tcwv_p = pos['tcwv']
    tcwv_n = neg['tcwv']
    tcwv_neut = neut['tcwv']


    p_t2m = stats.tukey_hsd(t2m_p, t2m_n, t2m_neut)
    p_msl = stats.tukey_hsd( msl_p, msl_n, msl_neut)
    p_tp = stats.tukey_hsd( tp_p, tp_n, tp_neut)
    p_d2m = stats.tukey_hsd( d2m_p, d2m_n, d2m_neut)
    p_tcwv = stats.tukey_hsd( tcwv_p, tcwv_n, tcwv_neut)



    print('Telecon: ', telecon)
    print('t2m: ', p_t2m)
    print('msl: ', p_msl)
    print('tp: ', p_tp)
    print('d2m: ', p_d2m)
    print('tcwv: ', p_tcwv)
    print('')

Telecon:  NAO
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.304     0.930    -2.270     1.662
 (0 - 2)      1.483     0.066    -0.074     3.039
 (1 - 0)      0.304     0.930    -1.662     2.270
 (1 - 2)      1.787     0.014     0.289     3.285
 (2 - 0)     -1.483     0.066    -3.039     0.074
 (2 - 1)     -1.787     0.014    -3.285    -0.289

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -2.679     0.999  -203.637   198.279
 (0 - 2)     37.458     0.845  -121.628   196.544
 (1 - 0)      2.679     0.999  -198.279   203.637
 (1 - 2)     40.137     0.812  -112.979   193.253
 (2 - 0)    -37.458     0.845  -196.544   121.628
 (2 - 1)    -40.137     0.812  -193.253   112.979

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.000     0.963    -0.000     0.000
 (0 - 2)      0.000     0.872    -0.000     0.000
 (1 - 0)      0.000     0.963    -0.000     0.000
 (1 - 2)      0.000     0.665    -0.000     0.000
 (2 - 0)     -0.000     0.872    -0.000     0.000
 (2 - 1)     -0.000     0.665    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.106     0.991    -2.046     1.834
 (0 - 2)      1.333     0.104    -0.202     2.869
 (1 - 0)      0.106     0.991    -1.834     2.046
 (1 - 2)      1.439     0.058    -0.039     2.917
 (2 - 0)     -1.333     0.104    -2.869     0.202
 (2 - 1)     -1.439     0.058    -2.917     0.039

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      0.363     0.767    -0.864     1.590
 (0 - 2)      1.249     0.007     0.277     2.220
 (1 - 0)     -0.363     0.767    -1.590     0.864
 (1 - 2)      0.886     0.068    -0.049     1.821
 (2 - 0)     -1.249     0.007    -2.220    -0.277
 (2 - 1)     -0.886     0.068    -1.821     0.049


Telecon:  NPGO
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.671     0.690    -2.592     1.250
 (0 - 2)      1.129     0.162    -0.323     2.581
 (1 - 0)      0.671     0.690    -1.250     2.592
 (1 - 2)      1.800     0.018     0.250     3.351
 (2 - 0)     -1.129     0.162    -2.581     0.323
 (2 - 1)     -1.800     0.018    -3.351    -0.250

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)    -40.366     0.879  -236.566   155.835
 (0 - 2)      2.918     0.999  -145.348   151.184
 (1 - 0)     40.366     0.879  -155.835   236.566
 (1 - 2)     43.284     0.797  -115.062   201.630
 (2 - 0)     -2.918     0.999  -151.184   145.348
 (2 - 1)    -43.284     0.797  -201.630   115.062

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.000     0.788    -0.000     0.000
 (0 - 2)     -0.000     0.936    -0.000     0.000
 (1 - 0)      0.000     0.788    -0.000     0.000
 (1 - 2)      0.000     0.876    -0.000     0.000
 (2 - 0)      0.000     0.936    -0.000     0.000
 (2 - 1)     -0.000     0.876    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.715     0.650    -2.609     1.180
 (0 - 2)      0.935     0.276    -0.496     2.366
 (1 - 0)      0.715     0.650    -1.180     2.609
 (1 - 2)      1.650     0.031     0.121     3.178
 (2 - 0)     -0.935     0.276    -2.366     0.496
 (2 - 1)     -1.650     0.031    -3.178    -0.121

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.687     0.373    -1.889     0.516
 (0 - 2)      0.250     0.795    -0.659     1.159
 (1 - 0)      0.687     0.373    -0.516     1.889
 (1 - 2)      0.937     0.061    -0.034     1.907
 (2 - 0)     -0.250     0.795    -1.159     0.659
 (2 - 1)     -0.937     0.061    -1.907     0.034


Telecon:  PDO
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.252     0.941    -2.026     1.522
 (0 - 2)     -0.653     0.526    -2.072     0.766
 (1 - 0)      0.252     0.941    -1.522     2.026
 (1 - 2)     -0.401     0.786    -1.827     1.025
 (2 - 0)      0.653     0.526    -0.766     2.072
 (2 - 1)      0.401     0.786    -1.025     1.827

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)   -176.056     0.057  -355.958     3.846
 (0 - 2)   -102.323     0.218  -246.202    41.556
 (1 - 0)    176.056     0.057    -3.846   355.958
 (1 - 2)     73.733     0.455   -70.842   218.309
 (2 - 0)    102.323     0.218   -41.556   246.202
 (2 - 1)    -73.733     0.455  -218.309    70.842

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      0.000     0.881    -0.000     0.000
 (0 - 2)      0.000     1.000    -0.000     0.000
 (1 - 0)     -0.000     0.881    -0.000     0.000
 (1 - 2)     -0.000     0.826    -0.000     0.000
 (2 - 0)     -0.000     1.000    -0.000     0.000
 (2 - 1)      0.000     0.826    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.282     0.924    -2.030     1.467
 (0 - 2)     -0.472     0.708    -1.870     0.927
 (1 - 0)      0.282     0.924    -1.467     2.030
 (1 - 2)     -0.190     0.946    -1.595     1.215
 (2 - 0)      0.472     0.708    -0.927     1.870
 (2 - 1)      0.190     0.946    -1.215     1.595

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      0.920     0.125    -0.186     2.027
 (0 - 2)      0.411     0.521    -0.474     1.296
 (1 - 0)     -0.920     0.125    -2.027     0.186
 (1 - 2)     -0.509     0.371    -1.399     0.380
 (2 - 0)     -0.411     0.521    -1.296     0.474
 (2 - 1)      0.509     0.371    -0.380     1.399


Telecon:  PNA
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -1.993     0.041    -3.922    -0.065
 (0 - 2)     -1.647     0.041    -3.243    -0.051
 (1 - 0)      1.993     0.041     0.065     3.922
 (1 - 2)      0.346     0.833    -1.067     1.759
 (2 - 0)      1.647     0.041     0.051     3.243
 (2 - 1)     -0.346     0.833    -1.759     1.067

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)    -82.622     0.586  -279.226   113.982
 (0 - 2)    -57.983     0.680  -220.729   104.763
 (1 - 0)     82.622     0.586  -113.982   279.226
 (1 - 2)     24.638     0.915  -119.462   168.739
 (2 - 0)     57.983     0.680  -104.763   220.729
 (2 - 1)    -24.638     0.915  -168.739   119.462

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.000     0.535    -0.000     0.000
 (0 - 2)      0.000     1.000    -0.000     0.000
 (1 - 0)      0.000     0.535    -0.000     0.000
 (1 - 2)      0.000     0.305    -0.000     0.000
 (2 - 0)     -0.000     1.000    -0.000     0.000
 (2 - 1)     -0.000     0.305    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -2.091     0.027    -3.990    -0.192
 (0 - 2)     -1.645     0.038    -3.217    -0.073
 (1 - 0)      2.091     0.027     0.192     3.990
 (1 - 2)      0.446     0.732    -0.945     1.838
 (2 - 0)      1.645     0.038     0.073     3.217
 (2 - 1)     -0.446     0.732    -1.838     0.945

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -1.274     0.035    -2.479    -0.070
 (0 - 2)     -0.870     0.101    -1.867     0.127
 (1 - 0)      1.274     0.035     0.070     2.479
 (1 - 2)      0.404     0.531    -0.479     1.287
 (2 - 0)      0.870     0.101    -0.127     1.867
 (2 - 1)     -0.404     0.531    -1.287     0.479

Telecon:  SOI
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      1.954     0.049     0.007     3.901
 (0 - 2)      0.644     0.583    -0.883     2.171
 (1 - 0)     -1.954     0.049    -3.901    -0.007
 (1 - 2)     -1.310     0.103    -2.818     0.198
 (2 - 0)     -0.644     0.583    -2.171     0.883
 (2 - 1)      1.310     0.103    -0.198     2.818

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     53.536     0.802  -144.974   252.046
 (0 - 2)     24.902     0.925  -130.742   180.546
 (1 - 0)    -53.536     0.802  -252.046   144.974
 (1 - 2)    -28.633     0.900  -182.362   125.095
 (2 - 0)    -24.902     0.925  -180.546   130.742
 (2 - 1)     28.633     0.900  -125.095   182.362

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.000     0.995    -0.000     0.000
 (0 - 2)     -0.000     0.931    -0.000     0.000
 (1 - 0)      0.000     0.995    -0.000     0.000
 (1 - 2)     -0.000     0.967    -0.000     0.000
 (2 - 0)      0.000     0.931    -0.000     0.000
 (2 - 1)      0.000     0.967    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      1.572     0.133    -0.349     3.492
 (0 - 2)      0.770     0.454    -0.736     2.275
 (1 - 0)     -1.572     0.133    -3.492     0.349
 (1 - 2)     -0.802     0.415    -2.290     0.685
 (2 - 0)     -0.770     0.454    -2.275     0.736
 (2 - 1)      0.802     0.415    -0.685     2.290

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      0.062     0.992    -1.158     1.282
 (0 - 2)      0.180     0.899    -0.777     1.136
 (1 - 0)     -0.062     0.992    -1.282     1.158
 (1 - 2)      0.118     0.954    -0.827     1.062
 (2 - 0)     -0.180     0.899    -1.136     0.777
 (2 - 1)     -0.118     0.954    -1.062     0.827


Telecon:  ENSO
t2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.555     0.758    -2.389     1.280
 (0 - 2)     -1.339     0.089    -2.829     0.152
 (1 - 0)      0.555     0.758    -1.280     2.389
 (1 - 2)     -0.784     0.396    -2.201     0.633
 (2 - 0)      1.339     0.089    -0.152     2.829
 (2 - 1)      0.784     0.396    -0.633     2.201

msl:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)    -11.494     0.989  -198.475   175.487
 (0 - 2)     16.702     0.964  -135.165   168.570
 (1 - 0)     11.494     0.989  -175.487   198.475
 (1 - 2)     28.196     0.891  -116.223   172.616
 (2 - 0)    -16.702     0.964  -168.570   135.165
 (2 - 1)    -28.196     0.891  -172.616   116.223

tp:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.000     0.960    -0.000     0.000
 (0 - 2)     -0.000     0.166    -0.000     0.000
 (1 - 0)      0.000     0.960    -0.000     0.000
 (1 - 2)     -0.000     0.267    -0.000     0.000
 (2 - 0)      0.000     0.166    -0.000     0.000
 (2 - 1)      0.000     0.267    -0.000     0.000

d2m:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)     -0.389     0.869    -2.197     1.420
 (0 - 2)     -1.107     0.180    -2.576     0.362
 (1 - 0)      0.389     0.869    -1.420     2.197
 (1 - 2)     -0.719     0.449    -2.116     0.678
 (2 - 0)      1.107     0.180    -0.362     2.576
 (2 - 1)      0.719     0.449    -0.678     2.116

tcwv:  Tukey's HSD Pairwise Group Comparisons (95.0% Confidence Interval)
Comparison  Statistic  p-value  Lower CI  Upper CI
 (0 - 1)      0.556     0.491    -0.591     1.703
 (0 - 2)     -0.130     0.943    -1.061     0.802
 (1 - 0)     -0.556     0.491    -1.703     0.591
 (1 - 2)     -0.686     0.164    -1.572     0.200
 (2 - 0)      0.130     0.943    -0.802     1.061
 (2 - 1)      0.686     0.164    -0.200     1.572

# TWO SAMPLE T TEST

In [3]:
%load_ext jupyter_capture_output

Jupyter Capture Output v0.0.11
The jupyter_capture_output module is not an IPython extension.

In [4]:
table = pd.read_csv(turbodir + 'stormtable_mslpert.csv', index_col=0)
t1 = table[(table['year']>=1970) & (table['AO Phase']=='Negative')]['t2m'].mean()
t2 = table[(table['year']>=1970) & (table['AO Phase']=='Positive')]['t2m'].mean()
print(t2-t1)

0.9439355202475213

In [7]:
%%capture_text --path "etc_ttest_pvalues.txt"
telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'ENSO','AO']

for telecon in telelist:
    n = '       '
    pt2m_list = ''
    pmsl_list = ''
    ptp_list = ''
    pd2m_list= ''
    pwv_list = ''
    for month in [None,10,11,12,1,2,3]:
        
        
        if month is None:
            p_mask = table[f'{telecon} Phase'] == 'Positive'
            n_mask = table[f'{telecon} Phase'] == 'Negative'
        else:
            p_mask = (table[f'{telecon} Phase']=='Positive')&(table['month_strongest_GLR']==month)
            n_mask = (table[f'{telecon} Phase']=='Negative')&(table['month_strongest_GLR']==month)

        # Use the mask to filter rows
        pos = table[p_mask]
        neg = table[n_mask]


        t2m_p = pos['t2m']
        t2m_n = neg['t2m']
        t2m_diff= np.nanmean(t2m_p)-np.nanmean(t2m_n)

        msl_p = pos['msl']
        msl_n = neg['msl']
        msl_diff= np.nanmean(msl_p)-np.nanmean(msl_n)

        tp_p = pos['tp']
        tp_n = neg['tp']
        tp_diff= np.nanmean(tp_p)-np.nanmean(tp_n)
        
        d2m_p = pos['d2m']
        d2m_n = neg['d2m']
        d2m_diff= np.nanmean(d2m_p)-np.nanmean(d2m_n)

        tcwv_p = pos['tcwv']
        tcwv_n = neg['tcwv']
        tcwv_diff= np.nanmean(tcwv_p)-np.nanmean(tcwv_n)
        
        n = n+str(len(tcwv_p))+','+str(len(tcwv_n))+'|'

        t2mstat, t2m  = stats.ttest_ind(t2m_p, t2m_n)
        mslstat, msl  = stats.ttest_ind(msl_p, msl_n)
        tpstat, tp    = stats.mannwhitneyu(tp_p, tp_n)
        d2mstat, d2m  = stats.ttest_ind(d2m_p, d2m_n)
        tcwvstat,tcwv = stats.ttest_ind(tcwv_p, tcwv_n)
        
        string=[]
        for var in [t2m,msl,tp,d2m,tcwv]:
            if var < 0.055:
                string.append('\033[1m')
                string.append('\033[0m')
            else:
                string.append('')
                string.append('')
        
        pt2m_list = pt2m_list+' '+string[0]+f'{t2m_diff:0.2f}({t2m:0.3f})'+string[1]
        pmsl_list = pmsl_list+' '+string[2]+f'{msl_diff/100:0.2f}({msl:0.3f})'+string[3]
        ptp_list = ptp_list+' '+string[4]+f'{tp_diff*1000:0.2f}({tp:0.3f})'+string[5]
        pd2m_list = pd2m_list+' '+string[6]+f'{d2m_diff:0.2f}({d2m:0.3f})'+string[7]
        pwv_list = pwv_list+' '+string[8]+f'{tcwv_diff:0.2f}({tcwv:0.3f})'+string[9]
    
    print('Telecon:','\033[1m'+telecon+'\033[0m','  OCT ','  NOV','  DEC','  JAN','  FEB','  MAR')
    print(n)
    print('t2m:  ', pt2m_list)
    print('msl:  ', pmsl_list)
    print('tp:   ',  ptp_list)
    print('d2m:  ', pd2m_list)
    print('tcwv: ', pwv_list)
    print('')

Output saved by overwring previous file at etc_ttest_pvalues.txt.
Telecon: NAO   OCT    NOV   DEC   JAN   FEB   MAR
       104,94|3,17|9,17|16,23|22,23|26,1|28,13|
t2m:    -0.95(0.337) 0.69(0.662) 2.26(0.093) -0.30(0.862) 0.92(0.620) -1.12(0.823) 4.67(0.026)
msl:    0.51(0.479) 3.85(0.176) 1.47(0.540) -1.07(0.490) 0.30(0.851) -5.01(0.375) 0.03(0.989)
tp:     -0.02(0.371) -0.05(0.416) -0.00(0.628) 0.03(0.400) -0.05(0.281) 0.14(0.296) 0.11(0.028)
d2m:    -0.94(0.337) 1.11(0.500) 2.64(0.043) 0.13(0.947) 1.44(0.387) -3.96(0.484) 4.94(0.006)
tcwv:   -0.40(0.500) 0.58(0.781) 2.01(0.083) 1.31(0.199) -1.14(0.284) 1.28(0.753) 4.33(0.000)

Telecon: NPGO   OCT    NOV   DEC   JAN   FEB   MAR
       142,129|29,19|33,26|10,30|18,16|22,18|30,20|
t2m:    2.37(0.007) 1.99(0.075) -0.27(0.801) 0.75(0.714) 3.24(0.151) 3.54(0.023) 1.41(0.434)
msl:    0.49(0.449) -0.54(0.675) 2.25(0.148) 0.42(0.828) -0.43(0.827) 0.07(0.972) -0.08(0.956)
tp:     -0.01(0.536) -0.01(0.950) -0.05(0.388) 0.03(0.606) 0.03(0.904) -0.02(0.817) -0.01(0.945)
d2m:    2.41(0.005) 2.17(0.038) -0.08(0.942) 0.56(0.798) 3.43(0.107) 4.10(0.016) 1.39(0.383)
tcwv:   0.86(0.134) 1.62(0.213) -0.28(0.808) 0.51(0.702) 0.88(0.574) 0.88(0.404) -0.02(0.987)

Telecon: PDO   OCT    NOV   DEC   JAN   FEB   MAR
       157,154|27,20|26,34|19,4|27,24|28,43|30,29|
t2m:    0.61(0.423) -1.32(0.208) -1.58(0.154) -0.01(0.996) -0.35(0.829) 1.45(0.232) 3.31(0.021)
msl:    -0.29(0.603) -1.40(0.313) 0.99(0.500) -1.78(0.497) -1.06(0.457) -1.16(0.310) 0.95(0.437)
tp:     0.01(0.699) -0.05(0.250) 0.00(0.840) -0.08(0.286) -0.00(0.902) 0.04(0.344) 0.05(0.392)
d2m:    0.50(0.512) -1.82(0.055) -1.38(0.222) -0.37(0.907) -1.52(0.360) 2.20(0.071) 2.82(0.024)
tcwv:   0.33(0.492) -2.27(0.039) -0.53(0.602) -0.06(0.973) -0.06(0.951) 1.85(0.021) 1.02(0.270)

Telecon: PNA   OCT    NOV   DEC   JAN   FEB   MAR
       102,141|9,29|24,31|18,16|18,7|16,27|17,31|
t2m:    -1.95(0.023) 0.42(0.739) -1.62(0.167) 0.39(0.829) 0.98(0.623) 0.74(0.536) 0.13(0.934)
msl:    0.69(0.244) -0.58(0.717) 1.43(0.276) 1.62(0.365) -1.60(0.426) 0.42(0.782) 1.08(0.401)
tp:     -0.03(0.194) 0.00(0.757) -0.03(0.593) -0.01(0.546) 0.03(0.790) 0.05(0.459) -0.07(0.161)
d2m:    -1.90(0.028) 0.83(0.483) -1.65(0.178) 0.34(0.861) 0.33(0.883) 1.05(0.414) -0.61(0.652)
tcwv:   -1.52(0.009) 1.55(0.275) -1.42(0.210) 0.41(0.733) -0.49(0.718) 1.08(0.263) -2.63(0.011)

Telecon: ENSO   OCT    NOV   DEC   JAN   FEB   MAR
       109,146|24,11|21,33|12,18|11,33|29,30|12,21|
t2m:    1.49(0.066) -1.21(0.363) -0.54(0.639) 0.59(0.718) 0.35(0.846) -0.07(0.951) 0.45(0.790)
msl:    0.42(0.504) -0.32(0.844) 3.57(0.014) 0.10(0.956) -0.58(0.727) 0.51(0.740) -1.80(0.260)
tp:     0.01(0.977) 0.02(0.845) -0.05(0.136) -0.04(0.983) 0.02(0.745) -0.01(0.519) 0.11(0.150)
d2m:    1.61(0.045) -0.77(0.495) -0.53(0.649) 1.05(0.553) 1.08(0.574) 0.43(0.701) -0.63(0.694)
tcwv:   0.99(0.066) -0.30(0.831) -0.83(0.468) 0.14(0.905) 0.98(0.325) -0.34(0.714) 1.67(0.193)

Telecon: AO   OCT    NOV   DEC   JAN   FEB   MAR
       127,112|5,12|13,5|24,32|19,25|29,13|37,25|
t2m:    0.43(0.615) 0.19(0.840) -0.15(0.945) -0.87(0.558) 3.53(0.053) -1.36(0.314) 1.29(0.361)
msl:    -1.36(0.037) 2.47(0.244) -4.46(0.100) -0.93(0.475) -0.77(0.660) -2.57(0.125) -2.31(0.084)
tp:     0.04(0.028) 0.03(0.959) 0.01(1.000) -0.00(0.579) 0.08(0.209) 0.02(0.399) 0.10(0.007)
d2m:    0.89(0.292) 0.62(0.576) -1.01(0.653) -0.91(0.566) 4.79(0.006) -1.39(0.330) 2.67(0.022)
tcwv:   0.65(0.235) 0.18(0.914) -1.90(0.440) 0.13(0.885) 0.68(0.481) -0.32(0.755) 3.42(0.000)

In [9]:
%%capture_text --path "etc_ttest_pvalues.txt"
telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'ENSO','AO']

table = pd.read_csv(turbodir + 'stormtable_mslpert.csv', index_col=0)

## THIS IS FOR A TEST!!!! BE SURE TO COMMENT THIS OUT LATER
table = table[(table['year']>=1970)]

for telecon in telelist:
    n = '       '
    pt2m_list = ''
    pmsl_list = ''
    ptp_list = ''
    pd2m_list= ''
    pwv_list = ''
    for month in [None,'greatlakes','alberta','colorado']:
        if month is None:
            p_mask = table[f'{telecon} Phase'] == 'Positive'
            n_mask = table[f'{telecon} Phase'] == 'Negative'
        else:
            p_mask = (table[f'{telecon} Phase']=='Positive')&(table['loc']==month)
            n_mask = (table[f'{telecon} Phase']=='Negative')&(table['loc']==month)

        # Use the mask to filter rows
        pos = table[p_mask]
        neg = table[n_mask]


        t2m_p = pos['t2m']
        t2m_n = neg['t2m']
        t2m_diff= np.nanmean(t2m_p)-np.nanmean(t2m_n)

        msl_p = pos['msl']
        msl_n = neg['msl']
        msl_diff= np.nanmean(msl_p)-np.nanmean(msl_n)

        tp_p = pos['tp']
        tp_n = neg['tp']
        tp_diff= np.nanmean(tp_p)-np.nanmean(tp_n)
        
        d2m_p = pos['d2m']
        d2m_n = neg['d2m']
        d2m_diff= np.nanmean(d2m_p)-np.nanmean(d2m_n)

        tcwv_p = pos['tcwv']
        tcwv_n = neg['tcwv']
        tcwv_diff= np.nanmean(tcwv_p)-np.nanmean(tcwv_n)
        
        n = n+str(len(tcwv_p))+','+str(len(tcwv_n))+'|'

        t2mstat, t2m  = stats.ttest_ind(t2m_p, t2m_n)
        mslstat, msl  = stats.ttest_ind(msl_p, msl_n)
        tpstat, tp    = stats.mannwhitneyu(tp_p, tp_n)
        d2mstat, d2m  = stats.ttest_ind(d2m_p, d2m_n)
        tcwvstat,tcwv = stats.ttest_ind(tcwv_p, tcwv_n)
        
        string=[]
        for var in [t2m,msl,tp,d2m,tcwv]:
            if var < 0.055:
                string.append('\033[1m')
                string.append('\033[0m')
            else:
                string.append('')
                string.append('')
        
        pt2m_list = pt2m_list+' '+string[0]+f'{t2m_diff:0.2f}({t2m:0.3f})'+string[1]
        pmsl_list = pmsl_list+' '+string[2]+f'{msl_diff/100:0.2f}({msl:0.3f})'+string[3]
        ptp_list = ptp_list+' '+string[4]+f'{tp_diff*1000:0.2f}({tp:0.3f})'+string[5]
        pd2m_list = pd2m_list+' '+string[6]+f'{d2m_diff:0.2f}({d2m:0.3f})'+string[7]
        pwv_list = pwv_list+' '+string[8]+f'{tcwv_diff:0.2f}({tcwv:0.3f})'+string[9]
    
    print('Telecon:','\033[1m'+telecon+'\033[0m','   GL ','  ALB','  COL')
    print(n)
    print('t2m:  ', pt2m_list)
    print('msl:  ', pmsl_list)
    print('tp:   ',  ptp_list)
    print('d2m:  ', pd2m_list)
    print('tcwv: ', pwv_list)
    print('')

Output saved by overwring previous file at etc_ttest_pvalues.txt.
Telecon: NAO    GL    ALB   COL
       104,94|42,50|31,24|18,12|
t2m:    -0.42(0.652) -1.14(0.399) -0.28(0.855) 1.71(0.508)
msl:    -0.49(0.666) 1.46(0.407) -1.54(0.374) -1.94(0.562)
tp:     -0.01(0.879) -0.04(0.404) 0.05(0.238) 0.12(0.300)
d2m:    -0.30(0.748) -0.91(0.521) 0.29(0.858) 1.79(0.424)
tcwv:   -0.02(0.976) -0.49(0.632) 0.70(0.489) 1.14(0.504)

Telecon: NPGO    GL    ALB   COL
       142,129|65,69|34,30|27,18|
t2m:    2.51(0.003) 4.17(0.001) 1.89(0.192) -0.94(0.614)
msl:    -0.56(0.572) -1.81(0.209) -0.24(0.894) 4.36(0.102)
tp:     -0.01(0.638) 0.04(0.536) -0.02(0.711) -0.09(0.233)
d2m:    2.51(0.003) 4.43(0.001) 1.76(0.219) -1.37(0.407)
tcwv:   1.23(0.067) 2.26(0.034) 0.48(0.616) 0.05(0.969)

Telecon: PDO    GL    ALB   COL
       157,154|71,74|39,35|19,29|
t2m:    0.59(0.406) -0.32(0.763) 2.27(0.135) 1.00(0.521)
msl:    -3.12(0.001) -3.20(0.014) -2.15(0.285) -1.89(0.399)
tp:     -0.02(0.793) -0.00(0.935) -0.03(0.369) -0.08(0.292)
d2m:    0.30(0.679) -0.22(0.838) 1.71(0.259) 0.58(0.659)
tcwv:   0.21(0.718) -0.19(0.834) 0.83(0.416) -0.02(0.986)

Telecon: PNA    GL    ALB   COL
       102,141|48,80|25,29|13,24|
t2m:    -1.96(0.017) -2.10(0.061) -0.94(0.574) -0.42(0.835)
msl:    -3.02(0.006) -3.06(0.047) -2.83(0.215) -0.46(0.884)
tp:     -0.09(0.017) -0.14(0.010) 0.01(0.876) -0.12(0.157)
d2m:    -2.01(0.017) -1.94(0.091) -1.30(0.462) -0.15(0.937)
tcwv:   -1.67(0.019) -1.74(0.088) -0.93(0.441) -0.02(0.989)

Telecon: ENSO    GL    ALB   COL
       109,146|66,73|23,35|8,25|
t2m:    1.36(0.067) 2.30(0.014) 1.80(0.202) -0.87(0.762)
msl:    -1.48(0.196) -2.50(0.110) 0.95(0.676) 5.13(0.217)
tp:     -0.01(0.636) 0.04(0.526) -0.06(0.266) -0.10(0.176)
d2m:    1.35(0.074) 2.17(0.024) 2.01(0.181) -0.99(0.703)
tcwv:   0.82(0.207) 1.64(0.056) 0.18(0.867) -0.88(0.648)

Telecon: AO    GL    ALB   COL
       127,112|65,52|31,29|22,13|
t2m:    0.94(0.248) 1.02(0.388) 1.86(0.209) 1.20(0.538)
msl:    -1.82(0.080) -1.48(0.306) -2.38(0.261) -3.29(0.307)
tp:     0.10(0.002) 0.12(0.030) 0.11(0.053) 0.11(0.157)
d2m:    1.67(0.044) 1.82(0.137) 2.75(0.066) 1.69(0.336)
tcwv:   1.13(0.086) 1.43(0.151) 2.01(0.042) 0.67(0.615)

In [28]:
table

,year,month,day,hour,lon,lat,loc,year_start_GLR,month_start_GLR,day_start_GLR,...,Unsupervised Class,AO,ENSO,NAO Phase,NPGO Phase,PDO Phase,PNA Phase,SOI Phase,ENSO Phase,AO Phase
0,1960,10,8,12,-96.00,46.00,alberta,1959,10,9,...,2,-0.2491,-0.165857,Neutral,Neutral,Positive,Neutral,Neutral,Neutral,Neutral
1,1960,10,10,12,-96.25,47.75,alberta,1959,10,11,...,2,-0.2491,-0.165857,Neutral,Neutral,Positive,Neutral,Neutral,Neutral,Neutral
2,1960,10,16,6,-93.25,48.75,greatlakes,1959,10,16,...,2,-0.2491,-0.165857,Neutral,Neutral,Positive,Neutral,Neutral,Neutral,Neutral
3,1960,10,23,18,-89.75,44.25,greatlakes,1959,10,23,...,2,-0.2491,-0.165857,Neutral,Neutral,Positive,Neutral,Neutral,Neutral,Neutral
4,1960,10,26,18,-77.25,43.00,greatlakes,1959,10,26,...,2,-0.2491,-0.165857,Neutral,Neutral,Positive,Neutral,Neutral,Neutral,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,2021,1,25,18,-94.00,36.25,NaN,2021,1,26,...,1,-2.4836,-1.918979,Negative,Neutral,Neutral,Neutral,Positive,Negative,Negative
882,2021,3,1,0,-82.75,47.25,greatlakes,2021,3,1,...,1,2.1092,-0.598879,Neutral,Neutral,Negative,Negative,Neutral,Neutral,Positive
883,2021,3,10,6,-101.25,39.25,colorado,2021,3,11,...,1,2.1092,-0.598879,Neutral,Neutral,Negative,Negative,Neutral,Neutral,Positive
884,2021,3,11,18,-80.25,49.75,greatlakes,2021,3,11,...,1,2.1092,-0.598879,Neutral,Neutral,Negative,Negative,Neutral,Neutral,Positive
885,2021,3,23,6,-97.75,36.75,colorado,2021,3,24,...,1,2.1092,-0.598879,Neutral,Neutral,Negative,Negative,Neutral,Neutral,Positive

# Mann Whitney U (i.e., non-parametric t-test (Jamie add-on))

In [6]:
%%capture_text --path "etc_mann-whitney_pvalues.txt"
telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'SOI', 'ENSO']

for telecon in telelist:
    n = '       '
    pt2m_list = ''
    pmsl_list = ''
    ptp_list = ''
    pd2m_list= ''
    pwv_list = ''
    for month in [None,10,11,12,1,2,3]:
        if month is None:
            p_mask = table[f'{telecon} Phase'] == 'Positive'
            n_mask = table[f'{telecon} Phase'] == 'Negative'
        else:
            p_mask = (table[f'{telecon} Phase']=='Positive')&(table['month_strongest_GLR']==month)
            n_mask = (table[f'{telecon} Phase']=='Negative')&(table['month_strongest_GLR']==month)

        # Use the mask to filter rows
        pos = table[p_mask]
        neg = table[n_mask]


        t2m_p = pos['t2m']
        t2m_n = neg['t2m']


        msl_p = pos['msl']
        msl_n = neg['msl']


        tp_p = pos['tp']
        tp_n = neg['tp']

        d2m_p = pos['d2m']
        d2m_n = neg['d2m']


        tcwv_p = pos['tcwv']
        tcwv_n = neg['tcwv']
        
        n = n+str(len(tcwv_p))+','+str(len(tcwv_n))+'|'

        t2mstat, t2m  = stats.mannwhitneyu(t2m_p, t2m_n)
        mslstat, msl  = stats.mannwhitneyu(msl_p, msl_n)
        tpstat, tp    = stats.mannwhitneyu(tp_p, tp_n)
        d2mstat, d2m  = stats.mannwhitneyu(d2m_p, d2m_n)
        tcwvstat,tcwv = stats.mannwhitneyu(tcwv_p, tcwv_n)
        
        string=[]
        for var in [t2m,msl,tp,d2m,tcwv]:
            if var < 0.055:
                string.append('\033[1m')
                string.append('\033[0m')
            else:
                string.append('')
                string.append('')
        
        pt2m_list = pt2m_list+' '+string[0]+f'{t2m:0.3f}'+string[1]
        pmsl_list = pmsl_list+' '+string[2]+f'{msl:0.3f}'+string[3]
        ptp_list = ptp_list+' '+string[4]+f'{tp:0.3f}'+string[5]
        pd2m_list = pd2m_list+' '+string[6]+f'{d2m:0.3f}'+string[7]
        pwv_list = pwv_list+' '+string[8]+f'{tcwv:0.3f}'+string[9]
    
    print('Telecon:','\033[1m'+telecon+'\033[0m','  OCT ','  NOV','  DEC','  JAN','  FEB','  MAR')
    print(n)
    print('t2m:  ', pt2m_list)
    print('msl:  ', pmsl_list)
    print('tp:   ',  ptp_list)
    print('d2m:  ', pd2m_list)
    print('tcwv: ', pwv_list)
    print('')

Output saved by overwring previous file at etc_mann-whitney_pvalues.txt.
Telecon: NAO   OCT    NOV   DEC   JAN   FEB   MAR
       124,136|10,30|22,16|21,19|21,34|23,14|27,23|
t2m:    0.842 0.542 0.337 0.058 0.842 0.790 0.276
msl:    0.664 0.241 0.220 0.766 0.242 0.088 0.785
tp:     0.924 0.295 0.584 0.914 0.235 0.145 0.471
d2m:    0.974 0.913 0.243 0.066 0.646 0.584 0.139
tcwv:   0.732 0.542 0.209 0.371 0.483 0.183 0.129

Telecon: NPGO   OCT    NOV   DEC   JAN   FEB   MAR
       148,126|30,12|31,30|8,28|18,16|24,17|37,23|
t2m:    0.243 0.900 0.983 0.926 0.849 0.011 0.338
msl:    0.695 0.770 0.834 0.562 0.343 0.272 0.750
tp:     0.507 0.073 0.629 0.421 0.221 0.199 0.648
d2m:    0.203 0.646 0.629 0.837 0.931 0.014 0.354
tcwv:   0.166 0.626 0.228 0.751 0.717 0.074 0.484

Telecon: PDO   OCT    NOV   DEC   JAN   FEB   MAR
       162,160|28,29|22,36|21,17|27,22|30,31|34,25|
t2m:    0.717 0.334 0.069 0.120 0.063 0.937 0.788
msl:    0.126 0.661 0.091 0.142 0.393 1.000 0.640
tp:     0.533 0.649 0.981 0.363 0.553 0.639 0.824
d2m:    0.699 0.311 0.028 0.168 0.115 0.925 0.860
tcwv:   0.062 0.228 0.879 0.977 0.063 0.857 0.969

Telecon: PNA   OCT    NOV   DEC   JAN   FEB   MAR
       118,159|17,26|18,31|28,29|21,7|18,29|16,37|
t2m:    0.012 0.434 0.909 0.478 0.249 0.058 0.090
msl:    0.556 0.931 0.811 0.393 0.466 0.887 0.649
tp:     0.243 0.576 0.860 0.731 0.249 0.269 0.809
d2m:    0.009 0.510 0.795 0.518 0.272 0.082 0.083
tcwv:   0.021 0.775 0.779 0.334 0.296 0.090 0.211

Telecon: SOI   OCT    NOV   DEC   JAN   FEB   MAR
       131,135|14,29|11,13|20,24|27,24|26,25|33,20|
t2m:    0.018 0.228 0.064 0.046 0.129 0.858 0.006
msl:    0.693 0.400 0.954 0.117 0.932 0.591 0.308
tp:     0.956 0.238 0.562 0.430 0.770 0.492 0.515
d2m:    0.042 0.085 0.093 0.092 0.144 0.947 0.010
tcwv:   0.958 0.007 0.772 0.068 0.246 0.888 0.267

Telecon: ENSO   OCT    NOV   DEC   JAN   FEB   MAR
       141,160|27,24|28,32|29,21|18,32|23,30|16,21|
t2m:    0.564 0.671 0.072 0.146 0.015 0.536 0.276
msl:    0.860 0.286 0.548 0.387 0.880 0.478 0.530
tp:     0.904 0.313 0.463 0.569 0.368 0.394 0.592
d2m:    0.708 0.445 0.019 0.298 0.013 0.713 0.382
tcwv:   0.189 0.011 0.589 0.263 0.028 0.809 0.724

In [7]:
# Wilcoxon option: ranksums (Jamie, 9/22/2024)
# The results match well with Mann-U Whitney in the previous code block.
from scipy.stats import ranksums # Import the appropriate scipy module

telelist = ['NAO', 'NPGO', 'PDO', 'PNA', 'SOI', 'ENSO']

for telecon in telelist:

    p_mask = table[f'{telecon} Phase'] == 'Positive'
    n_mask = table[f'{telecon} Phase'] == 'Negative'


    # Use the mask to filter rows
    pos = table[p_mask]
    neg = table[n_mask]


    #t2m_p = pos['t2m']
    #t2m_n = neg['t2m']
   

    #msl_p = pos['msl']
    #msl_n = neg['msl']
  

    tp_p = pos['tp']
    tp_n = neg['tp']

    #d2m_p = pos['d2m']
    #d2m_n = neg['d2m']


    #tcwv_p = pos['tcwv']
    #tcwv_n = neg['tcwv']

    #t2m = stats.mannwhitneyu(t2m_p, t2m_n).pvalue
    #msl = stats.mannwhitneyu(msl_p, msl_n).pvalue
    tp = stats.ranksums(tp_p, tp_n).pvalue
    #d2m = stats.mannwhitneyu(d2m_p, d2m_n).pvalue
    #tcwv = stats.mannwhitneyu(tcwv_p, tcwv_n).pvalue
    
    print(telecon)
    #print('t2m: ', t2m)
    #print('msl: ', msl)
    print('tp: ', tp)
    #print('d2m: ', d2m)
    #print('tcwv: ', tcwv)
    print('')

NAO
tp:  0.9237052446759983

NPGO
tp:  0.5067590063393235

PDO
tp:  0.5327926978821209

PNA
tp:  0.24283221343104822

SOI
tp:  0.9548696083653343

ENSO
tp:  0.9038732281107923

In [12]:
print((table['t2m'][table['PNA Phase']=='Positive']-273.15).mean())
print((table['t2m'][table['PNA Phase']=='Negative']-273.15).mean())

-2.3490428813559108
-0.3555684276729315

In [22]:
table[['year_strongest_GLR','month_strongest_GLR','PNA','PDO Phase','ENSO']]

     year_strongest_GLR  month_strongest_GLR       PNA PDO Phase      ENSO
0                  1959                   10  0.117287  Positive -0.165857
1                  1959                   10  0.117287  Positive -0.165857
2                  1959                   10  0.117287  Positive -0.165857
3                  1959                   10  0.117287  Positive -0.165857
4                  1959                   10  0.117287  Positive -0.165857
..                  ...                  ...       ...       ...       ...
881                2021                    1 -0.008944   Neutral -1.918979
882                2021                    3 -1.169641  Negative -0.598879
883                2021                    3 -1.169641  Negative -0.598879
884                2021                    3 -1.169641  Negative -0.598879
885                2021                    3 -1.169641  Negative -0.598879

[886 rows x 5 columns]

In [12]:
pd.read_csv('/nfs/turbo/seas-hutsona/shansen/sh_outputs/pna_cold.csv')

     Year  Month     Index
0    1959      1 -0.629576
1    1959      2 -0.639924
2    1959      3  0.579727
3    1959     10  0.117287
4    1959     11  0.336938
..    ...    ...       ...
373  2021      2 -0.509293
374  2021      3 -1.169641
375  2021     10  0.927918
376  2021     11  0.517570
377  2021     12 -2.762779

[378 rows x 3 columns]

In [25]:
test = pd.read_csv('/nfs/turbo/seas-hutsona/shansen/sh_outputs/stormtable_msl_pert.csv')
test[['year','month','PDO Phase']][table['PDO Phase']=='Negative']

     year  month PDO Phase
34   1962     10  Negative
35   1962     11   Neutral
36   1962     12   Neutral
37   1962     12   Neutral
38   1962     12   Neutral
..    ...    ...       ...
873  2020      3  Negative
882  2021      3  Negative
883  2021      3  Negative
884  2021      3  Negative
885  2021      3  Negative

[170 rows x 3 columns]

In [33]:
table[:50]['PDO Phase'],table[:50]['PDO Phase']=='Neutral'

(0     Positive
 1     Positive
 2     Positive
 3     Positive
 4     Positive
 5     Positive
 6     Positive
 7     Positive
 8      Neutral
 9      Neutral
 10     Neutral
 11     Neutral
 12     Neutral
 13     Neutral
 14     Neutral
 15     Neutral
 16     Neutral
 17     Neutral
 18     Neutral
 19     Neutral
 20     Neutral
 21     Neutral
 22     Neutral
 23     Neutral
 24     Neutral
 25     Neutral
 26     Neutral
 27     Neutral
 28     Neutral
 29     Neutral
 30     Neutral
 31     Neutral
 32     Neutral
 33     Neutral
 34    Negative
 35    Negative
 36    Negative
 37    Negative
 38    Negative
 39    Negative
 40    Negative
 41     Neutral
 42     Neutral
 43     Neutral
 44     Neutral
 45     Neutral
 46     Neutral
 47     Neutral
 48     Neutral
 49     Neutral
 Name: PDO Phase, dtype: object,
 0     False
 1     False
 2     False
 3     False
 4     False
 5     False
 6     False
 7     False
 8      True
 9      True
 10     True
 11     True
 12     True
 13     True
 14     True
 15     True
 16     True
 17     True
 18     True
 19     True
 20     True
 21     True
 22     True
 23     True
 24     True
 25     True
 26     True
 27     True
 28     True
 29     True
 30     True
 31     True
 32     True
 33     True
 34    False
 35    False
 36    False
 37    False
 38    False
 39    False
 40    False
 41     True
 42     True
 43     True
 44     True
 45     True
 46     True
 47     True
 48     True
 49     True
 Name: PDO Phase, dtype: bool)